import React,{useMemo,useState}from"react";import{createRoot}from"react-dom/client";import"./styles.css";
const questions=[
{id:1,section:"Math",skill:"Linear equations",difficulty:"Medium",prompt:"If 3x + 7 = 25, what is the value of x?",choices:["4","6","8","10"],answer:1,explanation:"Subtract 7 from both sides to get 3x = 18, then divide by 3. Therefore, x = 6.",tutor:["What operation would undo the +7?","Good. Now you have 3x = 18. What operation would undo the multiplication by 3?"]},
{id:2,section:"Reading & Writing",skill:"Transitions",difficulty:"Medium",prompt:"The first experiment produced an unexpected result. ___, the researchers repeated it with a larger sample.",choices:["However","Therefore","For example","Meanwhile"],answer:1,explanation:"The second action follows logically from the unexpected result, so 'Therefore' fits.",tutor:["Is the second action a contrast, an example, or a result?","Exactly. Which transition signals a result?"]},
{id:3,section:"Math",skill:"Percent change",difficulty:"Easy",prompt:"A jacket priced at $80 is discounted by 25%. What is the sale price?",choices:["$20","$55","$60","$75"],answer:2,explanation:"25% of $80 is $20, so the sale price is $60.",tutor:["What is 25% of $80?","Now subtract that discount from the original price."]},
{id:4,section:"Reading & Writing",skill:"Subject-verb agreement",difficulty:"Medium",prompt:"The collection of paintings ___ displayed in the west gallery.",choices:["are","were","is","have been"],answer:2,explanation:"The subject is the singular noun 'collection,' so 'is' agrees with the subject.",tutor:["What is the main subject: 'collection' or 'paintings'?","Right. Is 'collection' singular or plural?"]},
{id:5,section:"Math",skill:"Ratios",difficulty:"Easy",prompt:"If 4 notebooks cost $12, how much do 7 notebooks cost at the same rate?",choices:["$18","$21","$24","$28"],answer:1,explanation:"Each notebook costs $3, so 7 notebooks cost $21.",tutor:["First find the cost of one notebook.","Great. Multiply that unit price by 7."]},
{id:6,section:"Reading & Writing",skill:"Sentence boundaries",difficulty:"Medium",prompt:"The museum extended its hours; ___, attendance increased during the summer.",choices:["as a result","for instance","in contrast","nevertheless"],answer:0,explanation:"The attendance increase is a result of the extended hours, so 'as a result' establishes the correct relationship.",tutor:["What relationship exists between the two ideas?","Right—the second event follows from the first. Which choice signals a result?"]},
{id:7,section:"Math",skill:"Systems of equations",difficulty:"Medium",prompt:"If x + y = 11 and x - y = 3, what is x?",choices:["4","7","8","14"],answer:1,explanation:"Add the equations: 2x = 14, so x = 7.",tutor:["What happens if you add the two equations together?","Now solve the resulting equation for x."]},
{id:8,section:"Reading & Writing",skill:"Punctuation",difficulty:"Easy",prompt:"Which choice correctly completes the sentence? The scientist made one conclusion ___ the sample was too small.",choices:["; however,","because",", therefore,",": although"],answer:1,explanation:"'Because' correctly introduces the reason for the conclusion.",tutor:["Is the second clause giving a reason or a contrast?","Yes. Which choice introduces a reason?"]},
{id:9,section:"Math",skill:"Exponents",difficulty:"Easy",prompt:"What is the value of 2^3 + 4?",choices:["10","12","14","16"],answer:0,explanation:"2^3 = 8, and 8 + 4 = 12. Wait—that means the correct choice is 12, not 10.",tutor:["Evaluate the exponent first. What is 2^3?","Now add 4 to that result."]},
{id:10,section:"Reading & Writing",skill:"Central ideas",difficulty:"Medium",prompt:"A passage describes how a city converted an unused lot into a public garden. Which choice best states the passage's central idea?",choices:["Unused urban spaces can be repurposed for community benefit.","Gardens require daily maintenance.","Cities should prohibit vacant lots.","Public gardens are always inexpensive."],answer:0,explanation:"The passage centers on transforming an unused space into a community resource.",tutor:["What change is the passage mainly describing?","Exactly. Which answer captures that broader change?"]}
];
// Correct the intentionally simple exponent item so the bank itself is internally consistent.
questions[8].answer=1;questions[8].explanation="2^3 = 8, and 8 + 4 = 12.";
const empty={target:"1400",testDate:"",answers:{},confidence:{},started:false};
function load(){try{return{...empty,...JSON.parse(localStorage.getItem("p1600_profile")||"{}")}}catch{return empty}}
function App(){const[profile,setProfile]=useState(load);const[screen,setScreen]=useState(()=>localStorage.getItem("p1600_screen")||"home");const[index,setIndex]=useState(0);const[tutorStep,setTutorStep]=useState(0);const[tutorText,setTutorText]=useState("");const save=p=>{setProfile(p);localStorage.setItem("p1600_profile",JSON.stringify(p))};const go=s=>{setScreen(s);localStorage.setItem("p1600_screen",s)};const answers=profile.answers;const attempted=Object.keys(answers).length;const correct=Object.entries(answers).filter(([id,a])=>a===questions.find(q=>q.id===+id)?.answer).length;const accuracy=attempted?Math.round(correct/attempted*100):0;const current=questions[index];const stats=useMemo(()=>{let o={};questions.forEach(q=>{if(answers[q.id]===undefined)return;o[q.skill]??={total:0,correct:0,section:q.section};o[q.skill].total++;if(answers[q.id]===q.answer)o[q.skill].correct++});return Object.entries(o).map(([skill,d])=>({skill,...d,accuracy:Math.round(d.correct/d.total*100)})).sort((a,b)=>a.accuracy-b.accuracy)},[answers]);const mistakes=questions.filter(q=>answers[q.id]!==undefined&&answers[q.id]!==q.answer);const focus=stats.find(s=>s.accuracy<80)||stats[0];
const answer=c=>{save({...profile,answers:{...answers,[current.id]:c}});setTutorStep(0);setTutorText("")};const next=()=>{if(index<questions.length-1){setIndex(index+1);setTutorStep(0);setTutorText("")}else go("progress")};const reset=()=>{localStorage.clear();setProfile(empty);setScreen("home");setIndex(0)};
const nav=[['home','Home'],['practice','Practice'],['learn','Learn'],['progress','Progress']];return <div className="app"><header className="nav"><button className="brand" onClick={()=>go('home')}>PROJECT<span>1600</span></button><nav>{nav.map(([id,label])=><button className={screen===id?'active':''} onClick={()=>go(id)} key={id}>{label}</button>)}</nav></header>
{screen==='home'&&<main className="hero"><div className="eyebrow">ADAPTIVE SAT PREP · V0.3</div><h1>Stop studying everything.<br/><em>Study what you need.</em></h1><p className="lead">Project1600 learns how you make mistakes, then turns that information into a study experience built around you.</p><div className="hero-actions"><button className="primary" onClick={()=>go('practice')}>Start practicing →</button><button className="secondary" onClick={()=>go('learn')}>Explore Learn</button></div><div className="feature-row"><div><b>01</b><span>Diagnose</span><small>Find the skills costing you points.</small></div><div><b>02</b><span>Learn</span><small>Understand the concept before repeating it.</small></div><div><b>03</b><span>Master</span><small>Turn mistakes into permanent gains.</small></div></div></main>}
{screen==='practice'&&<main className="practice"><div className="practice-top"><span>PRACTICE · QUESTION {index+1} / {questions.length}</span><span>{current.section} · {current.difficulty}</span></div><div className="question-card"><div className="skill">{current.skill}</div><h2>{current.prompt}</h2><div className="choices">{current.choices.map((c,i)=><button key={c} className={'choice '+(answers[current.id]===i?'selected ':'')+(answers[current.id]!==undefined&&i===current.answer?'correct':'')} onClick={()=>answer(i)}><span>{String.fromCharCode(65+i)}</span>{c}</button>)}</div>{answers[current.id]!==undefined&&<div className={answers[current.id]===current.answer?'feedback good':'feedback bad'}><strong>{answers[current.id]===current.answer?'Correct.':'Not quite.'}</strong><p>{current.explanation}</p>{answers[current.id]!==current.answer&&<div className="tutor"><div className="tutor-head">🤖 Project1600 Tutor</div><div className="tutor-bubble">{tutorStep===0?"Let's figure out where things went wrong. "+current.tutor[0]:tutorStep<current.tutor.length?current.tutor[tutorStep]:"Nice. You worked through the step instead of just being given the answer."}</div>{tutorStep<current.tutor.length&&<div className="tutor-input"><input placeholder="Type your reasoning..." value={tutorText} onChange={e=>setTutorText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&tutorText.trim()&&(setTutorStep(tutorStep+1),setTutorText(''))}/><button className="primary" onClick={()=>{if(tutorText.trim()){setTutorStep(tutorStep+1);setTutorText('')}}}>Reply</button></div>}</div>}<div className="confidence"><span>How confident were you?</span>{['Low','Medium','High'].map(c=><button className={profile.confidence[current.id]===c?'selected':''} onClick={()=>save({...profile,confidence:{...profile.confidence,[current.id]:c}})} key={c}>{c}</button>)}</div><button className="primary" onClick={next}>{index===questions.length-1?'See progress →':'Next question →'}</button></div>}</div></main>}
{screen==='learn'&&<main className="tabs-page"><div className="page-head"><div className="eyebrow">LEARN</div><h2>Build the skill before you drill it.</h2><p>Short concept lessons give you a starting point, then send you straight into practice.</p></div><div className="lesson-grid">{[['∑','Linear equations','Isolate variables without losing track of signs.','Math'],['%','Percent change','Translate discounts and increases into equations.','Math'],['→','Transitions','Choose transitions by the logical relationship between ideas.','Reading & Writing'],['A','Grammar','Find the true subject before choosing a verb.','Reading & Writing'],['÷','Ratios','Use unit rates to make proportional relationships simple.','Math'],[';','Sentence boundaries','Know when a period, semicolon, or comma is needed.','Reading & Writing']].map(([icon,title,desc,tag])=><article className="lesson" key={title}><div className="icon">{icon}</div><h3>{title}</h3><p>{desc}</p><span className="tag">{tag}</span><br/><button className="secondary" style={{marginTop:16}} onClick={()=>go('practice')}>Practice this skill →</button></article>)}</div></main>}
{screen==='progress'&&<main className="tabs-page"><div className="page-head"><div className="eyebrow">PROGRESS</div><h2>Your progress is more than a score.</h2><p>Project1600 tracks the skills behind your answers so practice can become increasingly specific.</p></div><div className="progress-head"><div className="progress-ring" style={{'--progress':accuracy}}><span>{accuracy}%</span></div><div><div className="eyebrow">CURRENT ACCURACY</div><h3>{attempted?`${correct} of ${attempted} questions correct`:'No questions completed yet'}</h3><p>{focus?`Current focus: ${focus.skill}. Keep practicing to turn this into a strength.`:'Start Practice to build your first skill map.'}</p></div></div><section className="profile-grid"><div className="panel"><div className="eyebrow">SKILL MAP</div><h3>What we know so far</h3>{stats.length?stats.map(s=><div className="skill-row" key={s.skill}><div><b>{s.skill}</b><span>{s.section}</span></div><strong>{s.accuracy}%</strong></div>):<p>Complete some practice questions to see your skill map.</p>}</div><div className="panel"><div className="eyebrow">MISTAKE DNA</div><h3>{mistakes.length?`${mistakes.length} skill${mistakes.length===1?'':'s'} need review`:'No mistakes yet'}</h3>{mistakes.slice(0,3).map(q=><div className="mistake" key={q.id}><b>{q.skill}</b><p>Missed {q.choices[answers[q.id]]}; correct answer: {q.choices[q.answer]}.</p></div>)}{!mistakes.length&&<p>Your mistakes will become data for future personalized practice.</p>}<button className="primary" onClick={()=>go('practice')}>Keep practicing →</button></div></section></main>}
{screen==='onboarding'&&<main className="card-page"><div className="card"><div className="eyebrow">GET STARTED</div><h2>Build your first plan.</h2><p>Choose a target and start with a short diagnostic.</p><label>Target score</label><div className="score-options">{['1200','1300','1400','1500','1600'].map(s=><button className={profile.target===s?'selected':''} onClick={()=>save({...profile,target:s})} key={s}>{s}</button>)}</div><button className="primary wide" onClick={()=>go('practice')}>Start practicing →</button></div></main>}
<footer><button onClick={reset}>Reset demo data</button><span>Project1600 v0.3 · Interactive learning prototype</span></footer></div>}
createRoot(document.getElementById('root')).render(<App/>);